name: Delete PR Deployment

on:
  pull_request:
    types: [ closed ]

jobs:
  clean-pr-deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Prepare clean pr deployment
        id: prepare_deploy
        run: |
          mkdir ./empty-folder
          echo ::set-output name=folder::"pr/$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          repository-name: ${{ github.repository }}
          branch: gh-pages
          folder: ./empty-folder
          target-folder: ${{ steps.prepare_deploy.outputs.folder }}
          clean: true

          # https://github.com/crazy-max/ghaction-github-pages/blob/dev/src/git.ts#L3-L8
          commit-message: Deploy to GitHub pages
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
